# Generated by Django 2.1.5 on 2019-01-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretofindme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetidentity',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Internet Identities'},
        ),
        migrations.AlterField(
            model_name='internetidentity',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='internetidentity',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
