# Generated by Django 2.1.5 on 2019-01-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheretofindme', '0005_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('to_user__username',)},
        ),
    ]
