# Generated by Django 2.1.5 on 2019-01-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheretofindme', '0006_auto_20190111_2234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('from_user', 'to_user')},
        ),
    ]
