# Generated by Django 2.1.5 on 2019-01-21 19:46

from django.db import migrations
from django.db.models import Count


def forwards(apps, schema_editor):
    User = apps.get_model("wheretofindme", "User")
    for user in User.objects.annotate(Count("alias")).filter(alias__count=0):
        user.alias_set.create(name=user.username, seq=0)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("wheretofindme", "0009_alias")]

    operations = [migrations.RunPython(forwards, backwards)]
