# Generated by Django 2.1.5 on 2019-01-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wheretofindme", "0011_user_search_enabled")]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="nickname",
            field=models.CharField(blank=True, max_length=128),
        )
    ]
