# Generated by Django 2.1.5 on 2019-01-31 07:39

from django.db import migrations, models

ICON_CHOICES = (
    ("fas fa-link", "fas fa-link"),  # web
    ("fas fa-envelope", "fas fa-envelope"),  # email
    ("fab fa-behance", "fab fa-behance"),  # Behance
    ("fab fa-bitbucket", "fab fa-bitbucket"),  # Bitbucket
    ("fab fa-codepen", "fab fa-codepen"),  # Codepen
    ("fab fa-deviantart", "fab fa-deviantart"),  # Deviantart
    ("fab fa-diaspora", "fab fa-diaspora"),  # Diaspora
    ("fab fa-discord", "fab fa-discord"),  # Discord
    ("fab fa-dribbble", "fab fa-dribbble"),  # Dribbble
    ("fab fa-ello", "fab fa-ello"),  # Ello
    ("fab fa-etsy", "fab fa-etsy"),  # Etsy
    ("fab fa-facebook", "fab fa-facebook"),  # Facebook
    ("fab fa-github", "fab fa-github"),  # GitHub
    ("fab fa-gitlab", "fab fa-gitlab"),  # Gitlab
    ("fab fa-goodreads", "fab fa-goodreads"),  # Goodreads
    ("fab fa-google-plus-g", "fab fa-google-plus-g"),  # Google Plus
    ("fab fa-instagram", "fab fa-instagram"),  # Instagram
    ("fab fa-keybase", "fab fa-keybase"),  # Keybase
    ("fab fa-kickstarter", "fab fa-kickstarter"),  # Kickstarter
    ("fab fa-lastfm", "fab fa-lastfm"),  # Last
    ("fab fa-mastodon", "fab fa-mastodon"),  # Mastodon
    ("fab fa-medium", "fab fa-medium"),  # Medium
    ("fab fa-patreon", "fab fa-patreon"),  # Patreon
    ("fab fa-paypal", "fab fa-paypal"),  # Paypal
    ("fab fa-pinterest", "fab fa-pinterest"),  # Pinterest
    ("fab fa-ravelry", "fab fa-ravelry"),  # Ravelry
    ("fab fa-reddit", "fab fa-reddit"),  # Reddit
    ("fab fa-skype", "fab fa-skype"),  # Skype
    ("fab fa-slack", "fab fa-slack"),  # Slack
    ("fab fa-snapchat", "fab fa-snapchat"),  # Snapchat
    ("fab fa-soundcloud", "fab fa-soundcloud"),  # Soundcloud
    ("fab fa-stackoverflow", "fab fa-stackoverflow"),  # Stackoverflow
    ("fab fa-steam", "fab fa-steam"),  # Steam
    ("fab fa-teamspeak", "fab fa-teamspeak"),  # Teamspeak
    ("fab fa-tumblr", "fab fa-tumblr"),  # Tumblr
    ("fab fa-twitch", "fab fa-twitch"),  # Twitch
    ("fab fa-twitter", "fab fa-twitter"),  # Twitter
    ("fab fa-untappd", "fab fa-untappd"),  # Untappd
    ("fab fa-vimeo", "fab fa-vimeo"),  # Vimeo
    ("fab fa-youtube", "fab fa-youtube"),  # YouTube
)

QUALITY_CHOICES = ((0, "low"), (1, "mid"), (2, "high"))


class Migration(migrations.Migration):

    dependencies = [("wheretofindme", "0012_follow_nickname")]

    operations = [
        migrations.AddField(
            model_name="internetidentity",
            name="icon",
            field=models.CharField(
                choices=ICON_CHOICES, default="fas fa-link", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="internetidentity",
            name="quality",
            field=models.PositiveSmallIntegerField(choices=QUALITY_CHOICES, default=2),
        ),
        migrations.AddField(
            model_name="internetidentity",
            name="tag",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
