# Generated by Django 2.2 on 2019-04-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wheretofindme", "0014_populate_internetidentity_icon_field")]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
