# Generated by Django 3.2.16 on 2022-11-09 00:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wheretofindme", "0015_auto_20190403_0644"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="internetidentity",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="internetidentity",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fas fa-link", "fas fa-link"),
                    ("fas fa-envelope", "fas fa-envelope"),
                    ("fab fa-behance", "fab fa-behance"),
                    ("fab fa-bitbucket", "fab fa-bitbucket"),
                    ("fab fa-codepen", "fab fa-codepen"),
                    ("fab fa-deviantart", "fab fa-deviantart"),
                    ("fa fa-diaspora", "fa fa-diaspora"),
                    ("fa fa-discord", "fa fa-discord"),
                    ("fab fa-dribbble", "fab fa-dribbble"),
                    ("fab fa-ello", "fab fa-ello"),
                    ("fab fa-etsy", "fab fa-etsy"),
                    ("fab fa-facebook", "fab fa-facebook"),
                    ("fab fa-github", "fab fa-github"),
                    ("fab fa-gitlab", "fab fa-gitlab"),
                    ("fab fa-goodreads", "fab fa-goodreads"),
                    ("fab fa-google-plus-g", "fab fa-google-plus-g"),
                    ("fab fa-instagram", "fab fa-instagram"),
                    ("fa fa-keybase", "fa fa-keybase"),
                    ("fab fa-kickstarter", "fab fa-kickstarter"),
                    ("fab fa-lastfm", "fab fa-lastfm"),
                    ("fab fa-mastodon", "fab fa-mastodon"),
                    ("fa fa-matrix-org", "fa fa-matrix-org"),
                    ("fab fa-medium", "fab fa-medium"),
                    ("fa fa-patreon", "fa fa-patreon"),
                    ("fab fa-paypal", "fab fa-paypal"),
                    ("fab fa-pinterest", "fab fa-pinterest"),
                    ("fa fa-pixelfed", "fa fa-pixelfed"),
                    ("fab fa-ravelry", "fab fa-ravelry"),
                    ("fab fa-reddit", "fab fa-reddit"),
                    ("fab fa-skype", "fab fa-skype"),
                    ("fab fa-slack", "fab fa-slack"),
                    ("fab fa-snapchat", "fab fa-snapchat"),
                    ("fab fa-soundcloud", "fab fa-soundcloud"),
                    ("fab fa-stackoverflow", "fab fa-stackoverflow"),
                    ("fab fa-steam", "fab fa-steam"),
                    ("fab fa-teamspeak", "fab fa-teamspeak"),
                    ("fab fa-tumblr", "fab fa-tumblr"),
                    ("fab fa-twitch", "fab fa-twitch"),
                    ("fab fa-twitter", "fab fa-twitter"),
                    ("fab fa-untappd", "fab fa-untappd"),
                    ("fab fa-vimeo", "fab fa-vimeo"),
                    ("fab fa-youtube", "fab fa-youtube"),
                    ("fab fa-telegram", "fab fa-telegram"),
                    ("fab fa-linkedin", "fab fa-linkedin"),
                ],
                default="fas fa-link",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="first name",
            ),
        ),
    ]
