# Generated by Django 3.2.16 on 2022-11-09 04:58

from django.db import migrations


def forwards(apps, schema_editor):
    InternetIdentity = apps.get_model("wheretofindme", "InternetIdentity")
    mapping = {
        "fab fa-keybase": "fa fa-keybase",
        "fab fa-diaspora": "fab fa-diaspora",
        "fab fa-discord": "fab fa-discord",
        "fab fa-patreon": "fab fa-patreon",
    }
    for from_, to_ in mapping.items():
        InternetIdentity.objects.filter(icon=from_).update(icon=to_)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("wheretofindme", "0016_auto_20221109_0009"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
