# Generated by Django 3.2.16 on 2022-11-10 05:35

from django.db import migrations, models


def forwards(apps, schema_editor):
    InternetIdentity = apps.get_model("wheretofindme", "InternetIdentity")
    mapping = {
        "fab fa-mastodon": "fa fa-mastodon",
    }
    for from_, to_ in mapping.items():
        InternetIdentity.objects.filter(icon=from_).update(icon=to_)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("wheretofindme", "0017_change_fontawesome_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internetidentity",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fas fa-link", "fas fa-link"),
                    ("fas fa-envelope", "fas fa-envelope"),
                    ("fab fa-behance", "fab fa-behance"),
                    ("fab fa-bitbucket", "fab fa-bitbucket"),
                    ("fab fa-codepen", "fab fa-codepen"),
                    ("fab fa-deviantart", "fab fa-deviantart"),
                    ("fa fa-diaspora", "fa fa-diaspora"),
                    ("fa fa-discord", "fa fa-discord"),
                    ("fab fa-dribbble", "fab fa-dribbble"),
                    ("fab fa-ello", "fab fa-ello"),
                    ("fab fa-etsy", "fab fa-etsy"),
                    ("fab fa-facebook", "fab fa-facebook"),
                    ("fab fa-github", "fab fa-github"),
                    ("fab fa-gitlab", "fab fa-gitlab"),
                    ("fab fa-goodreads", "fab fa-goodreads"),
                    ("fab fa-google-plus-g", "fab fa-google-plus-g"),
                    ("fab fa-instagram", "fab fa-instagram"),
                    ("fa fa-keybase", "fa fa-keybase"),
                    ("fab fa-kickstarter", "fab fa-kickstarter"),
                    ("fab fa-lastfm", "fab fa-lastfm"),
                    ("fa fa-mastodon", "fa fa-mastodon"),
                    ("fa fa-matrix-org", "fa fa-matrix-org"),
                    ("fab fa-medium", "fab fa-medium"),
                    ("fa fa-patreon", "fa fa-patreon"),
                    ("fab fa-paypal", "fab fa-paypal"),
                    ("fab fa-pinterest", "fab fa-pinterest"),
                    ("fa fa-pixelfed", "fa fa-pixelfed"),
                    ("fab fa-ravelry", "fab fa-ravelry"),
                    ("fab fa-reddit", "fab fa-reddit"),
                    ("fab fa-skype", "fab fa-skype"),
                    ("fab fa-slack", "fab fa-slack"),
                    ("fab fa-snapchat", "fab fa-snapchat"),
                    ("fab fa-soundcloud", "fab fa-soundcloud"),
                    ("fab fa-stackoverflow", "fab fa-stackoverflow"),
                    ("fab fa-steam", "fab fa-steam"),
                    ("fab fa-teamspeak", "fab fa-teamspeak"),
                    ("fab fa-tumblr", "fab fa-tumblr"),
                    ("fab fa-twitch", "fab fa-twitch"),
                    ("fab fa-twitter", "fab fa-twitter"),
                    ("fab fa-untappd", "fab fa-untappd"),
                    ("fab fa-vimeo", "fab fa-vimeo"),
                    ("fab fa-youtube", "fab fa-youtube"),
                    ("fab fa-telegram", "fab fa-telegram"),
                    ("fab fa-linkedin", "fab fa-linkedin"),
                ],
                default="fas fa-link",
                max_length=50,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
