# Generated by Django 3.2.16 on 2022-11-10 05:51

from django.db import migrations


def forwards(apps, schema_editor):
    InternetIdentity = apps.get_model("wheretofindme", "InternetIdentity")
    mapping = {
        "fab fa-keybase": "fa fa-keybase",
        "fab fa-diaspora": "fa fa-diaspora",
        "fab fa-discord": "fa fa-discord",
        "fab fa-patreon": "fa fa-patreon",
    }
    for from_, to_ in mapping.items():
        InternetIdentity.objects.filter(icon=from_).update(icon=to_)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("wheretofindme", "0018_alter_internetidentity_icon"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
